# Generated by Django 2.0.2 on 2019-01-28 17:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190128_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 28, 17, 43, 4, 730717, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
