# Generated by Django 2.0.2 on 2019-01-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=10, verbose_name='Título'),
        ),
    ]
