# Generated by Django 2.0.2 on 2019-02-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_auto_20190124_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
