# Generated by Django 2.0.2 on 2019-02-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_auto_20190203_1930'),
        ('notices', '0003_auto_20190201_2144'),
    ]

    operations = [
    ]
